//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qgrepSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RegEx {
            get {
                return ((bool)(this["RegEx"]));
            }
            set {
                this["RegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaseSensitive {
            get {
                return ((bool)(this["CaseSensitive"]));
            }
            set {
                this["CaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowIncludes {
            get {
                return ((bool)(this["ShowIncludes"]));
            }
            set {
                this["ShowIncludes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExcludes {
            get {
                return ((bool)(this["ShowExcludes"]));
            }
            set {
                this["ShowExcludes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 35, 44")]
        public global::System.Drawing.Color BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColor"]));
            }
            set {
                this["ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("171, 173, 179")]
        public global::System.Drawing.Color BorderColor {
            get {
                return ((global::System.Drawing.Color)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 200, 215")]
        public global::System.Drawing.Color BorderHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["BorderHoverColor"]));
            }
            set {
                this["BorderHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 120, 215")]
        public global::System.Drawing.Color BorderSelectionColor {
            get {
                return ((global::System.Drawing.Color)(this["BorderSelectionColor"]));
            }
            set {
                this["BorderSelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color ResultFileColor {
            get {
                return ((global::System.Drawing.Color)(this["ResultFileColor"]));
            }
            set {
                this["ResultFileColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public global::System.Drawing.Color ResultTextColor {
            get {
                return ((global::System.Drawing.Color)(this["ResultTextColor"]));
            }
            set {
                this["ResultTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepSkyBlue")]
        public global::System.Drawing.Color ResultHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["ResultHighlightColor"]));
            }
            set {
                this["ResultHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49, 69, 87")]
        public global::System.Drawing.Color ResultHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["ResultHoverColor"]));
            }
            set {
                this["ResultHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 92, 148")]
        public global::System.Drawing.Color ResultSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["ResultSelectedColor"]));
            }
            set {
                this["ResultSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonColor"]));
            }
            set {
                this["ButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ButtonHoverColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonHoverColor"]));
            }
            set {
                this["ButtonHoverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color InputHintColor {
            get {
                return ((global::System.Drawing.Color)(this["InputHintColor"]));
            }
            set {
                this["InputHintColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 0, 0, 0")]
        public global::System.Drawing.Color OverlayBusyColor {
            get {
                return ((global::System.Drawing.Color)(this["OverlayBusyColor"]));
            }
            set {
                this["OverlayBusyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludesRegEx {
            get {
                return ((bool)(this["IncludesRegEx"]));
            }
            set {
                this["IncludesRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExcludesRegEx {
            get {
                return ((bool)(this["ExcludesRegEx"]));
            }
            set {
                this["ExcludesRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WholeWord {
            get {
                return ((bool)(this["WholeWord"]));
            }
            set {
                this["WholeWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TextButtonPressedColor {
            get {
                return ((global::System.Drawing.Color)(this["TextButtonPressedColor"]));
            }
            set {
                this["TextButtonPressedColor"] = value;
            }
        }
    }
}
