//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qgrepControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qgrepControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string AddFilterTitle {
            get {
                return ResourceManager.GetString("AddFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‹‹ Advanced.
        /// </summary>
        public static string AdvancedToggleContent {
            get {
                return ResourceManager.GetString("AdvancedToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather from solution.
        /// </summary>
        public static string AutomaticPopulationContent {
            get {
                return ResourceManager.GetString("AutomaticPopulationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ›› Basic.
        /// </summary>
        public static string BasicToggleContent {
            get {
                return ResourceManager.GetString("BasicToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clean index: {0}.
        /// </summary>
        public static string CannotCleanIndex {
            get {
                return ResourceManager.GetString("CannotCleanIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and update index.
        /// </summary>
        public static string CleanAndUpdateIndex {
            get {
                return ResourceManager.GetString("CleanAndUpdateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colors_schemes {
            get {
                object obj = ResourceManager.GetObject("colors_schemes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config{0}.
        /// </summary>
        public static string ConfigFormat {
            get {
                return ResourceManager.GetString("ConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location.
        /// </summary>
        public static string ConfigOpenContent {
            get {
                return ResourceManager.GetString("ConfigOpenContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path.
        /// </summary>
        public static string CopyFullPath {
            get {
                return ResourceManager.GetString("CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize shortcuts.
        /// </summary>
        public static string CustomizeShortcuts {
            get {
                return ResourceManager.GetString("CustomizeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize theme.
        /// </summary>
        public static string CustomizeTheme {
            get {
                return ResourceManager.GetString("CustomizeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string EditFilterTitle {
            get {
                return ResourceManager.GetString("EditFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit hotkeys.
        /// </summary>
        public static string EditHotkeys {
            get {
                return ResourceManager.GetString("EditHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude files....
        /// </summary>
        public static string ExcludeFilesLabel {
            get {
                return ResourceManager.GetString("ExcludeFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string ExcludeOptionContent {
            get {
                return ResourceManager.GetString("ExcludeOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        public static string FileAndLine {
            get {
                return ResourceManager.GetString("FileAndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter results....
        /// </summary>
        public static string FilterResultsLabel {
            get {
                return ResourceManager.GetString("FilterResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0}.
        /// </summary>
        public static string GroupFormat {
            get {
                return ResourceManager.GetString("GroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new group.
        /// </summary>
        public static string GroupsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group name.
        /// </summary>
        public static string GroupsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all groups.
        /// </summary>
        public static string GroupsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected group(s).
        /// </summary>
        public static string GroupsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsListBoxTitle {
            get {
                return ResourceManager.GetString("GroupsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened {0}.
        /// </summary>
        public static string HistoricOpen {
            get {
                return ResourceManager.GetString("HistoricOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched {0}.
        /// </summary>
        public static string HistoricSearch {
            get {
                return ResourceManager.GetString("HistoricSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recent searches ({0}).
        /// </summary>
        public static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include files....
        /// </summary>
        public static string IncludeFilesLabel {
            get {
                return ResourceManager.GetString("IncludeFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string IncludeOptionContent {
            get {
                return ResourceManager.GetString("IncludeOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Label.
        /// </summary>
        public static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Info.
        /// </summary>
        public static string InitInfo {
            get {
                return ResourceManager.GetString("InitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all results.
        /// </summary>
        public static string MenuCopyAllResults {
            get {
                return ResourceManager.GetString("MenuCopyAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path.
        /// </summary>
        public static string MenuCopyFullPath {
            get {
                return ResourceManager.GetString("MenuCopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy entire result.
        /// </summary>
        public static string MenuCopyResult {
            get {
                return ResourceManager.GetString("MenuCopyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        public static string MenuCopyText {
            get {
                return ResourceManager.GetString("MenuCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to location.
        /// </summary>
        public static string MenuGoTo {
            get {
                return ResourceManager.GetString("MenuGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search folders set..
        /// </summary>
        public static string NoSearchFoldersSet {
            get {
                return ResourceManager.GetString("NoSearchFoldersSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution loaded..
        /// </summary>
        public static string NoSolutionLoaded {
            get {
                return ResourceManager.GetString("NoSolutionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new folder(s).
        /// </summary>
        public static string PathsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit folder name.
        /// </summary>
        public static string PathsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all folders.
        /// </summary>
        public static string PathsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected folder(s).
        /// </summary>
        public static string PathsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string PathsListBoxTitle {
            get {
                return ResourceManager.GetString("PathsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        public static string PlainTextContent {
            get {
                return ResourceManager.GetString("PlainTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of predefined regexes.
        /// </summary>
        public static string PredefinedButtonTooltip {
            get {
                return ResourceManager.GetString("PredefinedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new config.
        /// </summary>
        public static string ProjectsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit config name.
        /// </summary>
        public static string ProjectsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all configs.
        /// </summary>
        public static string ProjectsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected config(s).
        /// </summary>
        public static string ProjectsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs.
        /// </summary>
        public static string ProjectsListBoxTitle {
            get {
                return ResourceManager.GetString("ProjectsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions ({0}).
        /// </summary>
        public static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx:.
        /// </summary>
        public static string RegExLabelContent {
            get {
                return ResourceManager.GetString("RegExLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra projects and groups to go back to basic settings.
        /// </summary>
        public static string RemoveExtraContent {
            get {
                return ResourceManager.GetString("RemoveExtraContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;.
        /// </summary>
        public static string RootContent {
            get {
                return ResourceManager.GetString("RootContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new filter.
        /// </summary>
        public static string RulesListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string RulesListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all filters.
        /// </summary>
        public static string RulesListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected filter(s).
        /// </summary>
        public static string RulesListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string RulesListBoxTitle {
            get {
                return ResourceManager.GetString("RulesListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonContent {
            get {
                return ResourceManager.GetString("SaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive ({0}).
        /// </summary>
        public static string SearchCaseSensitive {
            get {
                return ResourceManager.GetString("SearchCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search configurations.
        /// </summary>
        public static string SearchConfigurations {
            get {
                return ResourceManager.GetString("SearchConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search file....
        /// </summary>
        public static string SearchFileLabel {
            get {
                return ResourceManager.GetString("SearchFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole word ({0}).
        /// </summary>
        public static string SearchWholeWord {
            get {
                return ResourceManager.GetString("SearchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder(s).
        /// </summary>
        public static string SelectFolderPrompt {
            get {
                return ResourceManager.GetString("SelectFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} result(s) for &quot;{1}&quot;..
        /// </summary>
        public static string ShowingResults {
            get {
                return ResourceManager.GetString("ShowingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonContent {
            get {
                return ResourceManager.GetString("StopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme settings.
        /// </summary>
        public static string ThemeSettings {
            get {
                return ResourceManager.GetString("ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeLabelContent {
            get {
                return ResourceManager.GetString("TypeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update index.
        /// </summary>
        public static string UpdateIndex {
            get {
                return ResourceManager.GetString("UpdateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global path.
        /// </summary>
        public static string UseGlobalPathContent {
            get {
                return ResourceManager.GetString("UseGlobalPathContent", resourceCulture);
            }
        }
    }
}
