//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qgrepControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qgrepControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path.
        /// </summary>
        public static string AbsolutePathOptionContent {
            get {
                return ResourceManager.GetString("AbsolutePathOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add color override.
        /// </summary>
        public static string AddColorOverrideTooltip {
            get {
                return ResourceManager.GetString("AddColorOverrideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string AddFilterTitle {
            get {
                return ResourceManager.GetString("AddFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‹‹ Advanced.
        /// </summary>
        public static string AdvancedToggleContent {
            get {
                return ResourceManager.GetString("AdvancedToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string AlwaysOptionContent {
            get {
                return ResourceManager.GetString("AlwaysOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticOptionContent {
            get {
                return ResourceManager.GetString("AutomaticOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather from solution.
        /// </summary>
        public static string AutomaticPopulationContent {
            get {
                return ResourceManager.GetString("AutomaticPopulationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoOptionContent {
            get {
                return ResourceManager.GetString("AutoOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: bad repetition operator.
        /// </summary>
        public static string BadRepetitionOperator {
            get {
                return ResourceManager.GetString("BadRepetitionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ›› Basic.
        /// </summary>
        public static string BasicToggleContent {
            get {
                return ResourceManager.GetString("BasicToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building file table....
        /// </summary>
        public static string BuildingFileTableMessage {
            get {
                return ResourceManager.GetString("BuildingFileTableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building {0}.
        /// </summary>
        public static string BuildingMessage {
            get {
                return ResourceManager.GetString("BuildingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clean index: {0}.
        /// </summary>
        public static string CannotCleanIndex {
            get {
                return ResourceManager.GetString("CannotCleanIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}; {2}/{3} chunks updated in {4:0.00} sec.
        /// </summary>
        public static string ChunksUpdatedMessage {
            get {
                return ResourceManager.GetString("ChunksUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and update index.
        /// </summary>
        public static string CleanAndUpdateIndex {
            get {
                return ResourceManager.GetString("CleanAndUpdateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string ColorLabelContent {
            get {
                return ResourceManager.GetString("ColorLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color overrides.
        /// </summary>
        public static string ColorOverridesTitle {
            get {
                return ResourceManager.GetString("ColorOverridesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colors_schemes {
            get {
                object obj = ResourceManager.GetObject("colors_schemes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color scheme:.
        /// </summary>
        public static string ColorSchemeLabelContent {
            get {
                return ResourceManager.GetString("ColorSchemeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config{0}.
        /// </summary>
        public static string ConfigFormat {
            get {
                return ResourceManager.GetString("ConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location.
        /// </summary>
        public static string ConfigOpenContent {
            get {
                return ResourceManager.GetString("ConfigOpenContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path.
        /// </summary>
        public static string CopyFullPath {
            get {
                return ResourceManager.GetString("CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize shortcuts.
        /// </summary>
        public static string CustomizeShortcuts {
            get {
                return ResourceManager.GetString("CustomizeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize theme.
        /// </summary>
        public static string CustomizeTheme {
            get {
                return ResourceManager.GetString("CustomizeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: data file {0} has an out of date format, rebuilding.
        /// </summary>
        public static string DataFileOutOfDateFormatWarning {
            get {
                return ResourceManager.GetString("DataFileOutOfDateFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DaysAgoText {
            get {
                return ResourceManager.GetString("DaysAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit color override.
        /// </summary>
        public static string EditColorOverrideTooltip {
            get {
                return ResourceManager.GetString("EditColorOverrideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string EditFilterTitle {
            get {
                return ResourceManager.GetString("EditFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit hotkeys.
        /// </summary>
        public static string EditHotkeys {
            get {
                return ResourceManager.GetString("EditHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening data file {0} for writing.
        /// </summary>
        public static string ErrorOpeningDataFileForWriting {
            get {
                return ResourceManager.GetString("ErrorOpeningDataFileForWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data file {0}.
        /// </summary>
        public static string ErrorReadingDataFile {
            get {
                return ResourceManager.GetString("ErrorReadingDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file {0}.
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading folder {0}.
        /// </summary>
        public static string ErrorReadingFolder {
            get {
                return ResourceManager.GetString("ErrorReadingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading metadata for file {0}.
        /// </summary>
        public static string ErrorReadingMetadataForFile {
            get {
                return ResourceManager.GetString("ErrorReadingMetadataForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data file {0}.
        /// </summary>
        public static string ErrorSavingDataFile {
            get {
                return ResourceManager.GetString("ErrorSavingDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude files....
        /// </summary>
        public static string ExcludeFilesLabel {
            get {
                return ResourceManager.GetString("ExcludeFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude files:.
        /// </summary>
        public static string ExcludeFilesLabelContent {
            get {
                return ResourceManager.GetString("ExcludeFilesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string ExcludeOptionContent {
            get {
                return ResourceManager.GetString("ExcludeOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        public static string FileAndLine {
            get {
                return ResourceManager.GetString("FileAndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}): {2}.
        /// </summary>
        public static string FileLineErrorMessage {
            get {
                return ResourceManager.GetString("FileLineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File only.
        /// </summary>
        public static string FileOnlyOptionContent {
            get {
                return ResourceManager.GetString("FileOnlyOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileOptionContent {
            get {
                return ResourceManager.GetString("FileOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files, {1} Mb in, {2} Mb out.
        /// </summary>
        public static string FilesInAndOutMessage {
            get {
                return ResourceManager.GetString("FilesInAndOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter results....
        /// </summary>
        public static string FilterResultsLabel {
            get {
                return ResourceManager.GetString("FilterResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter results:.
        /// </summary>
        public static string FilterResultsLabelContent {
            get {
                return ResourceManager.GetString("FilterResultsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter search scope:.
        /// </summary>
        public static string FilterSearchScopeLabelContent {
            get {
                return ResourceManager.GetString("FilterSearchScopeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by:.
        /// </summary>
        public static string GroupByLabelContent {
            get {
                return ResourceManager.GetString("GroupByLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group expand:.
        /// </summary>
        public static string GroupExpandLabelContent {
            get {
                return ResourceManager.GetString("GroupExpandLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0}.
        /// </summary>
        public static string GroupFormat {
            get {
                return ResourceManager.GetString("GroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new group.
        /// </summary>
        public static string GroupsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group name.
        /// </summary>
        public static string GroupsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all groups.
        /// </summary>
        public static string GroupsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected group(s).
        /// </summary>
        public static string GroupsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("GroupsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsListBoxTitle {
            get {
                return ResourceManager.GetString("GroupsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened {0}.
        /// </summary>
        public static string HistoricOpen {
            get {
                return ResourceManager.GetString("HistoricOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched {0}.
        /// </summary>
        public static string HistoricSearch {
            get {
                return ResourceManager.GetString("HistoricSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recent searches ({0}).
        /// </summary>
        public static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History button:.
        /// </summary>
        public static string HistoryButtonLabelContent {
            get {
                return ResourceManager.GetString("HistoryButtonLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string HoursAgoText {
            get {
                return ResourceManager.GetString("HoursAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include files....
        /// </summary>
        public static string IncludeFilesLabel {
            get {
                return ResourceManager.GetString("IncludeFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include files:.
        /// </summary>
        public static string IncludeFilesLabelContent {
            get {
                return ResourceManager.GetString("IncludeFilesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string IncludeOptionContent {
            get {
                return ResourceManager.GetString("IncludeOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid character class.
        /// </summary>
        public static string InvalidCharacterClass {
            get {
                return ResourceManager.GetString("InvalidCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid character class range.
        /// </summary>
        public static string InvalidCharacterClassRange {
            get {
                return ResourceManager.GetString("InvalidCharacterClassRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid escape sequence.
        /// </summary>
        public static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid named capture group.
        /// </summary>
        public static string InvalidNamedCaptureGroup {
            get {
                return ResourceManager.GetString("InvalidNamedCaptureGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid perl operator.
        /// </summary>
        public static string InvalidPerlOperator {
            get {
                return ResourceManager.GetString("InvalidPerlOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid repetition size.
        /// </summary>
        public static string InvalidRepetitionSize {
            get {
                return ResourceManager.GetString("InvalidRepetitionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: invalid UTF-8.
        /// </summary>
        public static string InvalidUTF8 {
            get {
                return ResourceManager.GetString("InvalidUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNowText {
            get {
                return ResourceManager.GetString("JustNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last index update: {0}.
        /// </summary>
        public static string LastIndexUpdateLabelContent {
            get {
                return ResourceManager.GetString("LastIndexUpdateLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data file {0}: malformed chunk.
        /// </summary>
        public static string MalformedChunkErrorMessage {
            get {
                return ResourceManager.GetString("MalformedChunkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data file {0}: malformed header.
        /// </summary>
        public static string MalformedHeaderErrorReadingDataFile {
            get {
                return ResourceManager.GetString("MalformedHeaderErrorReadingDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all results.
        /// </summary>
        public static string MenuCopyAllResults {
            get {
                return ResourceManager.GetString("MenuCopyAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path.
        /// </summary>
        public static string MenuCopyFullPath {
            get {
                return ResourceManager.GetString("MenuCopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy entire result.
        /// </summary>
        public static string MenuCopyResult {
            get {
                return ResourceManager.GetString("MenuCopyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        public static string MenuCopyText {
            get {
                return ResourceManager.GetString("MenuCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to location.
        /// </summary>
        public static string MenuGoTo {
            get {
                return ResourceManager.GetString("MenuGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string MinutesAgoText {
            get {
                return ResourceManager.GetString("MinutesAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: missing ).
        /// </summary>
        public static string MissingClosingParenthesis {
            get {
                return ResourceManager.GetString("MissingClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: missing ].
        /// </summary>
        public static string MissingClosingSquareBracket {
            get {
                return ResourceManager.GetString("MissingClosingSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospace font:.
        /// </summary>
        public static string MonospaceFontLabelContent {
            get {
                return ResourceManager.GetString("MonospaceFontLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string NeverOptionContent {
            get {
                return ResourceManager.GetString("NeverOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string NeverText {
            get {
                return ResourceManager.GetString("NeverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: no argument for repetition operator.
        /// </summary>
        public static string NoArgumentForRepetitionOperator {
            get {
                return ResourceManager.GetString("NoArgumentForRepetitionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes.
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneOptionContent {
            get {
                return ResourceManager.GetString("NoneOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal font:.
        /// </summary>
        public static string NormalFontLabelContent {
            get {
                return ResourceManager.GetString("NormalFontLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search folders set..
        /// </summary>
        public static string NoSearchFoldersSet {
            get {
                return ResourceManager.GetString("NoSearchFoldersSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution loaded..
        /// </summary>
        public static string NoSolutionLoaded {
            get {
                return ResourceManager.GetString("NoSolutionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file search:.
        /// </summary>
        public static string OpenFileSearchLabelContent {
            get {
                return ResourceManager.GetString("OpenFileSearchLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file {0}: out of memory.
        /// </summary>
        public static string OutOfMemoryErrorReadingFile {
            get {
                return ResourceManager.GetString("OutOfMemoryErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override already exists!.
        /// </summary>
        public static string OverrideExistsErrorMessage {
            get {
                return ResourceManager.GetString("OverrideExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path only.
        /// </summary>
        public static string PathOnlyOptionContent {
            get {
                return ResourceManager.GetString("PathOnlyOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new folder(s).
        /// </summary>
        public static string PathsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit folder name.
        /// </summary>
        public static string PathsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all folders.
        /// </summary>
        public static string PathsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected folder(s).
        /// </summary>
        public static string PathsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("PathsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string PathsListBoxTitle {
            get {
                return ResourceManager.GetString("PathsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path style:.
        /// </summary>
        public static string PathStyleLabelContent {
            get {
                return ResourceManager.GetString("PathStyleLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        public static string PlainTextContent {
            get {
                return ResourceManager.GetString("PlainTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of predefined regular expressions.
        /// </summary>
        public static string PredefinedButtonTooltip {
            get {
                return ResourceManager.GetString("PredefinedButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new config.
        /// </summary>
        public static string ProjectsListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit config name.
        /// </summary>
        public static string ProjectsListBoxEditButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxEditButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all configs.
        /// </summary>
        public static string ProjectsListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected config(s).
        /// </summary>
        public static string ProjectsListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("ProjectsListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs.
        /// </summary>
        public static string ProjectsListBoxTitle {
            get {
                return ResourceManager.GetString("ProjectsListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions ({0}).
        /// </summary>
        public static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression:.
        /// </summary>
        public static string RegExLabelContent {
            get {
                return ResourceManager.GetString("RegExLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path.
        /// </summary>
        public static string RelativePathOptionContent {
            get {
                return ResourceManager.GetString("RelativePathOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all color overrides.
        /// </summary>
        public static string RemoveAllColorOverridesTooltip {
            get {
                return ResourceManager.GetString("RemoveAllColorOverridesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected color override(s).
        /// </summary>
        public static string RemoveColorOverrideTooltip {
            get {
                return ResourceManager.GetString("RemoveColorOverrideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra configs and groups to go back to basic settings.
        /// </summary>
        public static string RemoveExtraContent {
            get {
                return ResourceManager.GetString("RemoveExtraContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result group height:.
        /// </summary>
        public static string ResultGroupHeightLabelContent {
            get {
                return ResourceManager.GetString("ResultGroupHeightLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result line height:.
        /// </summary>
        public static string ResultLineHeightLabelContent {
            get {
                return ResourceManager.GetString("ResultLineHeightLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;.
        /// </summary>
        public static string RootContent {
            get {
                return ResourceManager.GetString("RootContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new filter.
        /// </summary>
        public static string RulesListBoxAddButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all filters.
        /// </summary>
        public static string RulesListBoxRemoveAllButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxRemoveAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected filter(s).
        /// </summary>
        public static string RulesListBoxRemoveButtonTooltip {
            get {
                return ResourceManager.GetString("RulesListBoxRemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string RulesListBoxTitle {
            get {
                return ResourceManager.GetString("RulesListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonContent {
            get {
                return ResourceManager.GetString("SaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning project....
        /// </summary>
        public static string ScanningProjectMessage {
            get {
                return ResourceManager.GetString("ScanningProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive ({0}).
        /// </summary>
        public static string SearchCaseSensitive {
            get {
                return ResourceManager.GetString("SearchCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search configurations.
        /// </summary>
        public static string SearchConfigurations {
            get {
                return ResourceManager.GetString("SearchConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search file....
        /// </summary>
        public static string SearchFileLabel {
            get {
                return ResourceManager.GetString("SearchFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search scope:.
        /// </summary>
        public static string SearchScopeLabelContent {
            get {
                return ResourceManager.GetString("SearchScopeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search while typing:.
        /// </summary>
        public static string SearchWhileTypingLabelContent {
            get {
                return ResourceManager.GetString("SearchWhileTypingLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole word ({0}).
        /// </summary>
        public static string SearchWholeWord {
            get {
                return ResourceManager.GetString("SearchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder(s).
        /// </summary>
        public static string SelectFolderPrompt {
            get {
                return ResourceManager.GetString("SelectFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut: {0}.
        /// </summary>
        public static string ShortcutTooltipFormat {
            get {
                return ResourceManager.GetString("ShortcutTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut: {0} (doesn&apos;t change setting).
        /// </summary>
        public static string ShortcutTooltipNoChangeFormat {
            get {
                return ResourceManager.GetString("ShortcutTooltipNoChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history:.
        /// </summary>
        public static string ShowHistoryLabelContent {
            get {
                return ResourceManager.GetString("ShowHistoryLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} result(s) for &quot;{1}&quot;..
        /// </summary>
        public static string ShowingResults {
            get {
                return ResourceManager.GetString("ShowingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history of opened files:.
        /// </summary>
        public static string ShowOpenHistoryLabelContent {
            get {
                return ResourceManager.GetString("ShowOpenHistoryLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonContent {
            get {
                return ResourceManager.GetString("StopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:.
        /// </summary>
        public static string TargetLabelContent {
            get {
                return ResourceManager.GetString("TargetLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and path.
        /// </summary>
        public static string TextAndPathOptionContent {
            get {
                return ResourceManager.GetString("TextAndPathOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text only.
        /// </summary>
        public static string TextOnlyOptionContent {
            get {
                return ResourceManager.GetString("TextOnlyOptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme settings.
        /// </summary>
        public static string ThemeSettings {
            get {
                return ResourceManager.GetString("ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle case sensitive:.
        /// </summary>
        public static string ToggleCaseSensitiveLabelContent {
            get {
                return ResourceManager.GetString("ToggleCaseSensitiveLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle exclude files:.
        /// </summary>
        public static string ToggleExcludeFilesLabelContent {
            get {
                return ResourceManager.GetString("ToggleExcludeFilesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle filter results:.
        /// </summary>
        public static string ToggleFilterResultsLabelContent {
            get {
                return ResourceManager.GetString("ToggleFilterResultsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle grouping by:.
        /// </summary>
        public static string ToggleGroupingByLabelContent {
            get {
                return ResourceManager.GetString("ToggleGroupingByLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle grouping expand:.
        /// </summary>
        public static string ToggleGroupingExpandLabelContent {
            get {
                return ResourceManager.GetString("ToggleGroupingExpandLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle include files:.
        /// </summary>
        public static string ToggleIncludeFilesLabelContent {
            get {
                return ResourceManager.GetString("ToggleIncludeFilesLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle regular expressions:.
        /// </summary>
        public static string ToggleRegexLabelContent {
            get {
                return ResourceManager.GetString("ToggleRegexLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle whole word:.
        /// </summary>
        public static string ToggleWholeWordLabelContent {
            get {
                return ResourceManager.GetString("ToggleWholeWordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: trailing \.
        /// </summary>
        public static string TrailingBackslash {
            get {
                return ResourceManager.GetString("TrailingBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim spaces on copy:.
        /// </summary>
        public static string TrimSpacesOnCopyLabelContent {
            get {
                return ResourceManager.GetString("TrimSpacesOnCopyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeLabelContent {
            get {
                return ResourceManager.GetString("TypeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncaught exception: {0}.
        /// </summary>
        public static string UncaughtExceptionMessage {
            get {
                return ResourceManager.GetString("UncaughtExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: unexpected ).
        /// </summary>
        public static string UnexpectedClosingParenthesis {
            get {
                return ResourceManager.GetString("UnexpectedClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing regular expression: unexpected error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update index.
        /// </summary>
        public static string UpdateIndex {
            get {
                return ResourceManager.GetString("UpdateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update index automatically:.
        /// </summary>
        public static string UpdateIndexAutomaticallyLabelContent {
            get {
                return ResourceManager.GetString("UpdateIndexAutomaticallyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}:.
        /// </summary>
        public static string UpdatingMessage {
            get {
                return ResourceManager.GetString("UpdatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use global path.
        /// </summary>
        public static string UseGlobalPathContent {
            get {
                return ResourceManager.GetString("UseGlobalPathContent", resourceCulture);
            }
        }
    }
}
